### PR TITLE
fixed run on summit like system

### PR DESCRIPTION
**Pull request by max9901**
fix het

### CODE REVIEW

**Comment by llandsmeer** [comment]
No

**Comment by max9901** [comment]
yes

**Comment by llandsmeer** [comment]
Can we at least add guards to the `-mcpu=native` option for power9?

**Comment by max9901** [comment]
no

**Comment by llandsmeer** [comment]
ok

**Comment by llandsmeer** [comment]
Ill merge if u creat issue 4 this

**Review by llandsmeer — COMMENTED** [review]
Ugly code

**Review by llandsmeer — APPROVED** [review]
Ok

**Pull request merged**
